DELETE http://localhost:8080/events/3
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlcy5jb20iLCJleHAiOjE3MTU2MDg1MTIsInVzZXJJZCI6Mn0.wp2csCmQDOcET4MAifVZPmt6abOqGSrYMAMz3N_1gBQ